The problem is that the victim do not verify that the transfer 
is successfully executed.

payable(king).transfer(msg.value);

The attacker makes the transfer fail and the entire transaction 
reverts. 
    
receive() external payable {
        require(false, "you cannot claim the throne!");
    }


Most of Ethernaut's levels try to expose (in an oversimplified form of course) 
something that actually happened â€” a real hack or a real bug.

In this case, see: King of the Ether and King of the Ether Postmortem.

https://www.kingoftheether.com/thrones/kingoftheether/index.html

https://www.kingoftheether.com/postmortem.html


